### ISSUE TITLE
USBasp incredibly slow?

### ISSUE THREAD

**Issue by MCUdude** [nerdralph/usbasp#3] opened 2020-10-07 13:14 UTC
I just re-flashed one of my USBISP's with your firmware. However, for some reason, the USBISP with the new firmware is incredibly slow! It takes about 16 times as long as some of my older USBasp's that always run at full speed. Do you know what causes this? Attached is the hex file for compiled for ATmega88.

[main.hex.zip](https://github.com/nerdralph/usbasp/files/5340887/main.hex.zip)

**Comment by nerdralph** [comment] 2020-10-07 14:19
I had something similar happen a couple times before I disabled turbo mode, but couldn't reproduce it.  There may be an issue with the speed negotiation.  There's What is the target MCU?

**Comment by MCUdude** [comment] 2020-10-07 14:51
I could reproduce this issue when trying to flash a USBISP programmer with an ATmega88 and an ATmega88P, and another development board I tested on that had an ATmega1284P (running at 16 MHz)

**Comment by nerdralph** [comment] 2020-10-07 16:02
I can sometimes reproduce the issue when trying to flash a t88 with a usbasp running my m8 firmware, but I can't consistently reproduce it.  When it does happen, unplugging and re-plugging the usbasp gets it working at the fast speed again.
I only have one m88, so I can't exactly duplicate your setup.  Given that I'm sometimes (20-30% of the time) getting the slow speed problem with the t88 target, I should eventually be able to track it down.

**Comment by nerdralph** [comment] 2020-10-07 19:55
I still haven't been able to consistently reproduce the problem.  The few times it has happened, if I unplug the usbasp and plug it back in, it runs at full speed, and continues to run at full speed for subsequent invocations of avrdude.
Do you power the target from the USBISP, or does the target have it's own power connection?  If you unplug the USBISP from the USB port and plug it back in, is it still slow?

**Comment by MCUdude** [comment] 2020-10-07 19:57
I do power the target from the USBISP. It doesn't matter if I unplug it, and put it back in. It's slow no matter what.

What's strange is that I loaded the exact same hex file as I did a few weeks ago. Then everything worked just fine!

**Comment by MCUdude** [comment] 2020-11-21 17:41
Did you figure this one out?

**Comment by nerdralph** [comment] 2020-11-21 19:02
I've been using a slightly modified version for the past month and a half without encountering the problem.  I forgot to push the change.  Thanks for the reminder.

It's only a small change to how the SCK timing is set/reset.  I just pushed the change and made a 1.07 release.

**Comment by MCUdude** [comment] 2020-11-21 19:05
Thanks! I'll give it a try soon.

**Comment by MCUdude** [comment] 2020-11-22 19:31
Weird. I just flashed your new m88.hex file to mu USBISP hardware, and it is exactly as slow as when I use the -B32 flag.
A 608-byte hex files take according to Avrdude 4.75 seconds to write to an ATtiny13 (running at 9.6 MHz).

**Comment by nerdralph** [comment] 2020-11-22 21:42
Which avrdude version are you using?  On windows I'm using 6.3-20190619, and set the driver to libusbK with Zadig.
I just re-tested a full flash dump using a lcsoft usbasp with a m8 and it finishes in < 0.5s.
```
$ avrdude -c usbasp -p t13 -U flash:r:dump.hex:i

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude.exe: Device signature = 0x1e9007 (probably t13)
avrdude.exe: reading flash memory:

Reading | ################################################## | 100% 0.45s

avrdude.exe: writing output file "dump.hex"

avrdude.exe: safemode: Fuses OK (E:FF, H:FF, L:72)

avrdude.exe done.  Thank you.
```

**Comment by nerdralph** [comment] 2020-11-22 22:00
I just tested under Linux (Ubuntu 18.04) with avrdude 6.3-4, and the flash dump completes in 0.29s.

**Comment by MCUdude** [comment] 2020-11-22 22:31
I'm using the Avrdude version Arduino 1.8.13 ships with: `Avrdude Version 6.3-20190619`

I'm using a Mac, so I can't just use Zadig.

Here is my "dump" with a USBISP using your firmware:
```
$ avrdude -C/Users/hans/Documents/Arduino/hardware/MicroCore/avr/avrdude.conf -c usbasp -p t13 -U flash:r:dump.hex:i

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x1e9007 (probably t13a)
avrdude: reading flash memory:

Reading | ################################################## | 100% 4.61s

avrdude: writing output file "dump.hex"

avrdude: safemode: Fuses OK (E:FF, H:FB, L:3A)

avrdude done.  Thank you.

```

Here is a dump with another USBISP using the firmware hosted [here](https://github.com/MCUdude/USBISP):
```
$ avrdude -C/Users/hans/Documents/Arduino/hardware/MicroCore/avr/avrdude.conf -c usbasp -p t13 -U flash:r:dump.hex:i

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9007 (probably t13a)
avrdude: reading flash memory:

Reading | ################################################## | 100% 0.23s

avrdude: writing output file "dump.hex"

avrdude: safemode: Fuses OK (E:FF, H:FB, L:3A)

avrdude done.  Thank you.

```

**Comment by nerdralph** [comment] 2020-11-23 04:49
Damn.  Since the Mac is BSD-based, it should work quite similar to Linux.
I'll examine the code some more to see if I can deduce what might be happening.  It is significant that it's not dropping to the slowest speed of 0.5Hz, which means the speed detection is not completely failing.

**Comment by nerdralph** [comment] 2020-11-25 14:23
My fuse settings were FF 72, so I changed them to match yours (FB 3A), but I still can't reproduce the problem.  I've tried 3V3 & 5V.  Are you using your little t13 dev board?  I've been testing on a breadboard, so I may dig out the dev board you sent me to try to duplicate your setup as close as possible.

When I was rewriting the firmware, I noticed the original version doesn't follow the datasheet's recommendation (section 17.6.1) to wait 20ms after pulsing reset.
https://github.com/MCUdude/usbisp/blob/master/firmware/src/isp.c#L204

If I still can't duplicate the problem when I try with a different t13 and using your dev board, do you think you could hook up a scope or logic analyzer to the SPI lines?

**Comment by MCUdude** [comment] 2020-11-25 19:25
> Are you using your little t13 dev board?

Yes, that's correct.

> do you think you could hook up a scope or logic analyzer to the SPI lines?

Good thing the little board I've made makes it very easy to hook up oscilloscope probes to. Here's what I get from
`avrdude -C/path/to/avrdude.conf -c usbasp -p t13 -U flash:r:dump.hex:i`


This is the entire capture. Channels are labled, so it should be straight forward. Look (delay) time after trigger in the upper left corner to figure out when all this happened relative to the first RST falling edge (that I triggered on):
![DS1Z_QuickPrint2](https://user-images.githubusercontent.com/3238730/100272618-c3e49900-2f5b-11eb-9c50-c0f051e14837.png)



This is the initializing part:
![DS1Z_QuickPrint3](https://user-images.githubusercontent.com/3238730/100272657-d1018800-2f5b-11eb-9984-e756f258c280.png)


Zoomed in on the first pulses that appears on the SCK line:
![DS1Z_QuickPrint4](https://user-images.githubusercontent.com/3238730/100272698-dfe83a80-2f5b-11eb-81eb-db9374e16e37.png)

Even further zoomed in on the first data:
![DS1Z_QuickPrint5](https://user-images.githubusercontent.com/3238730/100272828-132ac980-2f5c-11eb-88cc-da1a6398e46d.png)

This is what comes after the initialization (i think). This looks to me like the actual dump.
![DS1Z_QuickPrint6](https://user-images.githubusercontent.com/3238730/100272863-2047b880-2f5c-11eb-8a9b-edfed002cded.png)

**Comment by MCUdude** [comment] 2020-11-25 19:48
For reference, here's the output from the same Avrdude command, but with another USBISP that runs the firmware I host:


Entire capture
![DS1Z_QuickPrint7](https://user-images.githubusercontent.com/3238730/100274791-52a6e500-2f5f-11eb-81f1-dd34665e76d9.png)

First clock pulses appearing on the SCK line
![DS1Z_QuickPrint8](https://user-images.githubusercontent.com/3238730/100274806-55a1d580-2f5f-11eb-8d10-fa1e85971489.png)

Data that goes on and on after the first pulses (actual dump I think)
![DS1Z_QuickPrint9](https://user-images.githubusercontent.com/3238730/100274809-576b9900-2f5f-11eb-9c9c-3333b9af7a69.png)


Zoomed in on the data that goes on and on (actual dump I think)
![DS1Z_QuickPrint10](https://user-images.githubusercontent.com/3238730/100274816-59cdf300-2f5f-11eb-922a-ac292b9f1786.png)

**Comment by nerdralph** [comment] 2020-11-26 01:23
That helps a lot.  It's not dropping down to a slow speed - it is starting
off slow.  That helps narrow down the issue.

**Comment by nerdralph** [comment] 2020-11-26 03:27
I forgot to remove the code for the slow sck jumper on PC2.  The input
floats, and if it reads as 0, the SPI clock rate is set to 8kHz.  I'll
remove the code and push the change after some quick testing.

**Comment by nerdralph** [comment] 2020-11-26 12:57
You can try the changed version now.

**Comment by MCUdude** [comment] 2020-11-26 18:24
Thanks, that actually solved the issue!

Another thing I discovered is that it struggling with a real slow clock like the internal 128 kHz watchdog source. Here is the Avrdude output from a dump when the T13 is running at 128kHz:

```
$ avrdude -C/Users/hans/Documents/Arduino/hardware/MicroCore/avr/avrdude.conf -c usbasp -p t13 -U flash:r:dump.hex:i

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e9007 (probably t13a)
avrdude: reading flash memory:

Reading | ################################################## | 100% 2.03s

avrdude: writing output file "dump.hex"

avrdude: safemode: Verify error - unable to read lfuse properly. Programmer may not be reliable.
avrdude: safemode: Verify error - unable to read lfuse properly. Programmer may not be reliable.
avrdude: safemode: Sorry, reading back fuses was unreliable. I have given up and exited programming mode

avrdude done.  Thank you.
```

According to my scope, it seems like it's picking a clock speed of ~32 kHz, which maybe just a little bit too fast. But hey, the T13 did the initial reply when it got a 32 kHz clock pulse. BTW no issues with a system clock of 600kHz (SCK speed of ~93kHz)

**Comment by MCUdude** [comment] 2020-11-26 18:26
Oh, is it correct that the maximum SCK speed with your firmware is about 1.51 MHz, compared to "my" firmware that only gets  ~700kHz?

**Comment by nerdralph** [comment] 2020-11-26 21:04
The issue at 128kHz makes sense, given the clock is actually closer to 115kHz.   I could chose  one speed lower than the first speed that works, but that would slow it down at all the other clock speeds.  Does anyone actually use 128kHz in real projects?  I'm inclined to leave the code as it is, since you can still limit the speed with the -B option if you **REALLY** want to use 128kHz.

As for the top speed, yes, it is 1.5Mhz.   I even added support for 3Mhz, but it's not enabled.

**Comment by nerdralph** [comment] 2020-11-26 21:05
Fixed with https://github.com/nerdralph/usbasp/commit/5ba7cf5ef9abb8ab3e0886d6f6e00cfebbc65950

**Closed as completed by nerdralph** 2020-11-26 21:05 UTC

**Comment by MCUdude** [comment] 2020-11-26 21:14
> The issue at 128kHz makes sense, given the clock is actually closer to 115kHz. I could chose one speed lower than the first speed that works, but that would slow it down at all the other clock speeds. Does anyone actually use 128kHz in real projects? I'm inclined to leave the code as it is, since you can still limit the speed with the -B option if you REALLY want to use 128kHz.

It's better that it picks the fastest clock, rather than the second fastest. Probably no one is using the 128 kHz WDT as their main clock. It's slow and inaccurate. I tried it because it's the slowest clock MicroCore supports. Just leave the code like it is, it's excellent!

>  I even added support for 3Mhz, but it's not enabled.

Any reason why this isn't enabled? Reliability issues?

**Comment by nerdralph** [comment] 2020-11-26 23:05
> 
> > I even added support for 3Mhz, but it's not enabled.
> 
> Any reason why this isn't enabled? Reliability issues?

It worked fine, but was not much faster than 1.5Mhz given the overhead of v-USB.
